@HostAddress=http://localhost:4004
#@HostAddress=https://localhost:10001
#@HostAddress=http://gemini-eda-alb-641893049.us-east-1.elb.amazonaws.com
#@HostAddress=http://localhost:5000

GET {{HostAddress}}/customers/2249262b-6641-4a28-b578-374701066274

###

POST {{HostAddress}}/customers
Content-Type: application/json

{
    "firstName": "JohnT",
    "lastName": "DoeT",
    "email": "johnt.doet@example.com",
    "createUser": true,
    "password": "SecurePassword123!"
}

###

POST {{HostAddress}}/customers
Content-Type: application/json

{
    "firstName": "Hubert",
    "lastName": "Dumas",
    "email": "hubertd@example.com",
    "createUser": true,
    "password": "SecurePassword123!"
}

###

POST {{HostAddress}}/customers/authenticate
Content-Type: application/json

{
    "username": "hubertd@example.com",
    "password": "SecurePassword123!"
}

### ADDRESS

POST {{HostAddress}}/customers/2249262b-6641-4a28-b578-374701066274/addresses
Content-Type: application/json

{
    "addressLine1": "123 Main St",
    "addressLine2": "Apt 4B",
    "city": "New York",
    "state": "NY",
    "postCode": "10001",
    "country": "US",
    "isDefault": true
}

### ADDRESS - Using full country name (also supported)

POST {{HostAddress}}/customers/2249262b-6641-4a28-b578-374701066274/addresses
Content-Type: application/json

{
    "addressLine1": "456 Oak Ave",
    "city": "Toronto",
    "state": "ON",
    "postCode": "M5V 3A8",
    "country": "Canada",
    "isDefault": false
}